language: node_js
node_js:
    -"7.5"
script:
    - npm install -g @angular/cli
    - npm install
install:
    - npm install -g sw-precache
    - npm install -g firebase-tools
after_success:
    - ng build -prod --aot --verbose
    - sw-precache --root=dist --static-file-globs='dist/**/*.*'
    - firebase deploy --token "$FIREBASE_TOKEN"



